### PR TITLE
add ability to templatize the application configuration

### PR DESCRIPTION
**Pull request by karthik2804**
Add the ability to use Application variables to configure the `address`, `username`, `password`, and `topic` fields.

### CODE REVIEW

**Comment by suneetnangia** [comment]
Thank you, looks good.

**Review by suneetnangia — DISMISSED** [review]
Looks good, raised minor suggestion re Readme for @karthik2804 to consider, not too precious about it. 
Thanks

**Comment by karthik2804** [comment]
@suneetnangia I moved the readme to the suggested location.

**Review by suneetnangia — APPROVED** [review]
LGTM, Thanks.

**Pull request merged**
